target = "latest"
no_ssl_verify = false
ignore_warning = false
show_full_path = false
upgrade = false
no_color = false
filter = [
]
ignores =[
    {%- if cookiecutter.package_manager == "conda" %}
    "python"
    {%- endif %}
]
